const config=window.CAFE_CCP_CONFIG||{};const bookingApiUrl=config.bookingApiUrl||sessionStorage.getItem('cafeCcpBookingApiUrl')||'';
const orderId=new URLSearchParams(location.search).get('orderId')||'';
const elements={loading:document.getElementById('payment-loading'),details:document.getElementById('payment-details'),error:document.getElementById('payment-error'),order:document.getElementById('order-id'),pkg:document.getElementById('package-name'),amount:document.getElementById('amount'),transfer:document.getElementById('transfer-content'),status:document.getElementById('payment-status'),confirm:document.getElementById('manual-confirm'),bank:document.getElementById('bank-name'),accountName:document.getElementById('account-name'),accountNo:document.getElementById('account-no')};
let pollTimer;
function formatVnd(value){return new Intl.NumberFormat('vi-VN',{style:'currency',currency:'VND'}).format(value)}
async function api(action,method='GET',data){if(!bookingApiUrl)throw new Error('Booking API chưa được cấu hình.');if(method==='GET'){const url=new URL(bookingApiUrl);url.searchParams.set('action',action);url.searchParams.set('orderId',orderId);const response=await fetch(url,{credentials:'omit'});return response.json()}const response=await fetch(bookingApiUrl,{method:'POST',credentials:'omit',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,data})});return response.json()}
function render(order){elements.loading.hidden=true;elements.details.hidden=false;elements.order.textContent=order.orderId;elements.pkg.textContent=order.packageName;elements.amount.textContent=formatVnd(order.amount);elements.transfer.textContent=order.transferContent;elements.status.textContent=order.status;elements.bank.textContent=order.payment?.bankName||'Chưa cấu hình ngân hàng';elements.accountName.textContent=order.payment?.accountName||'';elements.accountNo.textContent=order.payment?.accountNo||'';if(['PAID','CONFIRMED','COMPLETED'].includes(order.status)){clearTimeout(pollTimer);location.replace(`thankyou.html?orderId=${encodeURIComponent(order.orderId)}&status=${encodeURIComponent(order.status)}`)}}
async function load(){try{if(!orderId)throw new Error('Thiếu mã đơn.');const payload=await api('checkPayment');if(!payload.ok)throw new Error(payload.error?.message||'Không tải được đơn.');render(payload.data);pollTimer=setTimeout(load,10000)}catch(error){elements.loading.hidden=true;elements.error.textContent=error.message}}
elements.confirm.addEventListener('click',async()=>{elements.confirm.disabled=true;try{const payload=await api('manualConfirm','POST',{orderId});if(!payload.ok)throw new Error(payload.error?.message);elements.status.textContent=payload.data.status;elements.confirm.textContent='Đã gửi yêu cầu đối soát'}catch(error){elements.error.textContent=error.message;elements.confirm.disabled=false}});
load();
