const fs=require('fs');const vm=require('vm');const path=require('path');const root=path.resolve(__dirname,'..');
function read(file){return fs.readFileSync(path.join(root,file),'utf8')}
function assert(condition,message){if(!condition)throw new Error(message)}
const context={window:{}};vm.createContext(context);vm.runInContext(read('config.js'),context);vm.runInContext(read('data.js'),context);
const packages=context.window.CAFE_CCP_FALLBACK.packages;assert(packages.length===4,'Fallback phải có đúng 4 gói ban đầu');
assert(new Set(packages.map(item=>item.code)).size===packages.length,'Package code phải duy nhất');
packages.forEach(item=>{assert(item.price>0,`Giá ${item.code} phải dương`);assert(item.duration>0,`Thời lượng ${item.code} phải dương`);assert(['phút','giờ'].includes(item.unit),`Đơn vị ${item.code} không hợp lệ`)});
const html=read('index.html');['config.js','data.js','script.js'].forEach(file=>assert(html.includes(`src="${file}"`),`Thiếu ${file} trong index.html`));
assert((html.match(/data-content-key=/g)||[]).length>=26,'Landing phải có mapping Content Sheet cho các nội dung chính');
assert(!html.includes('class="pkg-btn" id="btn-pkg2" style='),'CTA package không được dùng style inline ghi đè theme');
['payment.html','thankyou.html','admin/index.html','vercel.json'].forEach(file=>assert(fs.existsSync(path.join(root,file)),`Thiếu ${file}`));
const bookingBackend=read('apps-script/booking-payment/Code.gs');packages.forEach(item=>assert(bookingBackend.includes(`'${item.code}'`),`Backend thiếu package ${item.code}`));
['normalizeOrderId_','INVALID_STATE','Last Updated At'].forEach(term=>assert(bookingBackend.includes(term),`Booking backend thiếu contract ${term}`));
['Số điện thoại Việt Nam không hợp lệ','Ngày đặt lịch không hợp lệ hoặc đã ở trong quá khứ','Asia/Ho_Chi_Minh'].forEach(term=>assert(bookingBackend.includes(term),`Booking validation thiếu ${term}`));
const contentBackend=read('apps-script/content-admin/Code.gs');['saveNavigation','saveSection','saveUser'].forEach(action=>assert(contentBackend.includes(`body.action === '${action}'`),`Content backend thiếu action ${action}`));
assert(contentBackend.includes("!/^https:\\/\\//i.test(href)"),'Navigation phải chặn URL không an toàn');
['Content type chỉ hỗ trợ text hoặc attribute','Attribute không nằm trong allowlist','URL nội dung không an toàn'].forEach(message=>assert(contentBackend.includes(message),`Content validation thiếu: ${message}`));
['Package code không hợp lệ','Giá gói phải là số nguyên hợp lệ','Thời lượng phải từ 5 đến 1.440 phút','Icon URL không an toàn'].forEach(message=>assert(contentBackend.includes(message),`Package validation thiếu: ${message}`));
assert(contentBackend.includes("requireSession_(body.token, ['admin'])"),'API user phải chỉ cho admin');
['Bạn không thể tự hạ quyền','Phải giữ ít nhất một admin'].forEach(message=>assert(contentBackend.includes(message),`User guard thiếu: ${message}`));
['contentPublic_','navigationPublic_','sectionPublic_'].forEach(mapper=>assert(contentBackend.includes(`.map(${mapper})`),`Public API thiếu allowlist mapper ${mapper}`));
assert(contentBackend.includes("const PUBLIC_CACHE_KEY = 'public-init-v3'"),'Public cache key phải tăng khi contract đổi');
assert(contentBackend.includes('missingContent')&&contentBackend.includes('existingContentKeys'),'Content seed phải migration idempotent cho Sheet hiện có');
['bookingRemoteHealth_','operationsSummary_','UrlFetchApp.fetch'].forEach(term=>assert(contentBackend.includes(term),`Admin dashboard backend thiếu ${term}`));
assert(contentBackend.includes('script\\.google\\.com|script\\.googleusercontent\\.com'),'Booking health endpoint phải giới hạn Google Apps Script');
const adminHtml=read('admin/index.html');['navigation-panel','sections-panel','users-panel'].forEach(id=>assert(adminHtml.includes(`id="${id}"`),`Admin thiếu panel ${id}`));
assert(adminHtml.includes('booking-web-app-url')&&contentBackend.includes('saveBookingConfig'),'Admin phải cấu hình được Booking Script');
const adminScript=read('admin/app.js');assert(adminScript.includes("await api('saveUser', record)"),'Admin UI thiếu lưu user');assert(!adminScript.includes('Password Hash'),'Admin UI không được đọc hoặc hiển thị password hash');
['renderContentRecords','createContentEditor','Preview an toàn'].forEach(term=>assert(adminScript.includes(term),`Content editor thiếu ${term}`));
['renderPackages','createPackageEditor',"await api('savePackage', record)"].forEach(term=>assert(adminScript.includes(term),`Package editor thiếu ${term}`));
['editor-heading','package-fields','package-details','editor-actions','content-editor-body'].forEach(term=>assert(adminScript.includes(term),`Admin editor thiếu cấu trúc ${term}`));
['Tên hiển thị trên trang chủ','sectionLabels','managed-row'].forEach(term=>assert(adminScript.includes(term)||read('admin/style.css').includes(term),`Admin menu/section thiếu ${term}`));
['switch-button','order-button','Đã cập nhật thứ tự hiển thị'].forEach(term=>assert(adminScript.includes(term)||read('admin/style.css').includes(term),`Admin menu/section thiếu điều khiển ${term}`));
['renderHealthOverview','content-health','booking-health','recent-errors'].forEach(term=>assert(adminScript.includes(term)||adminHtml.includes(`id="${term}"`),`Admin dashboard thiếu ${term}`));
['payment-tab','payment-config-form','payment-bank-code','payment-webhook-status'].forEach(id=>assert(adminHtml.includes(`id="${id}"`),`Admin thanh toán thiếu ${id}`));
['payment-connection-form','payment-booking-web-app-url','payment-booking-admin-secret'].forEach(id=>assert(adminHtml.includes(`id="${id}"`),`Admin kết nối thanh toán thiếu ${id}`));
['renderPaymentConfig',"api('savePaymentConfig'",'paymentMode'].forEach(term=>assert(adminScript.includes(term)||contentBackend.includes(term),`Admin thanh toán thiếu contract ${term}`));
assert(adminScript.includes("api('saveBookingConfig',{bookingWebAppUrl,bookingAdminSecret})"),'Admin phải lưu được URL và secret dạng write-only');
['getPaymentConfig','savePaymentConfig','BOOKING_ADMIN_SECRET'].forEach(term=>assert(bookingBackend.includes(term),`Booking admin config thiếu ${term}`));
assert(contentBackend.includes("body.action === 'savePaymentConfig'")&&contentBackend.includes('bookingAdminRequest_'),'Content admin phải chuyển cấu hình thanh toán sang Booking Script');
const landingScript=read('script.js');['renderContent','renderNavigation','renderSections','renderPublicData'].forEach(name=>assert(landingScript.includes(`function ${name}(`),`Landing thiếu renderer ${name}`));
assert(landingScript.includes("fetch('/api/config'"),'Landing phải lấy CONTENT_API_URL runtime từ Vercel /api/config');
assert(!landingScript.includes('window.open(`${appConfig.messengerUrl'),'Form booking không được fallback sang Facebook/Messenger');
assert(read('api/config.js').includes('bookingApiUrl'),'Runtime config phải cấp Booking API trực tiếp');
['normalizeVietnamPhone','todayLocalIso','validateBookingForm','Ngày đặt lịch không được ở trong quá khứ'].forEach(term=>assert(landingScript.includes(term),`Frontend booking validation thiếu ${term}`));
assert(read('migration-kit/content.csv').split('\n').length>=27,'Migration content phải chứa đầy đủ key landing chính');
assert(read('migration-kit/section-order.csv').includes('Section Key,Order,Visible,Label'),'Migration section phải có tên tiếng Việt');
const paymentScript=read('payment.js');['POLL_DELAYS','POLL_MAX_MS','visibilitychange','STOP_STATUSES'].forEach(term=>assert(paymentScript.includes(term),`Payment polling thiếu ${term}`));
['payment-qr','payment-mode','copy-transfer'].forEach(id=>assert(read('payment.html').includes(`id="${id}"`),`Payment UI thiếu ${id}`));
['PAYMENT_MODE','PAYMENT_BANK_CODE','paymentQrUrl_','Payment Transaction ID','PAYMENT_MISMATCH'].forEach(term=>assert(bookingBackend.includes(term),`Payment backend thiếu ${term}`));
const sepayProxy=read('api/sepay-webhook.js');['SEPAY_API_KEY','PAYMENT_WEBHOOK_SECRET','timingSafeEqual','Apikey'].forEach(term=>assert(sepayProxy.includes(term),`SePay proxy thiếu ${term}`));
const vercelConfig=JSON.parse(read('vercel.json'));const cspHeaders=vercelConfig.headers.flatMap(rule=>rule.headers).filter(header=>header.key==='Content-Security-Policy');assert(cspHeaders.every(header=>header.value.includes('https://img.vietqr.io')),'Mọi CSP áp dụng cho payment phải cho phép ảnh QR VietQR');
assert(paymentScript.includes("elements.qr.style.display = qrUrl ? 'block' : 'none'"),'Payment phải ẩn ảnh QR lỗi thay vì giữ khung trắng');
const thankyouScript=read('thankyou.js');assert(thankyouScript.includes("url.searchParams.set('action', 'checkPayment')"),'Thank-you phải xác minh trạng thái từ backend');assert(!thankyouScript.includes("params.get('status')"),'Thank-you không được tin status từ URL');
['thankyou-package','thankyou-amount','next-heading'].forEach(id=>assert(read('thankyou.html').includes(`id="${id}"`),`Thank-you chuyên nghiệp thiếu ${id}`));
['booking-success-modal','booking-success-payment','booking-success-countdown'].forEach(id=>assert(html.includes(`id="${id}"`),`Popup đăng ký thiếu ${id}`));
['bookingCustomerEmailHtml_','PUBLIC_SITE_URL','htmlBody'].forEach(term=>assert(bookingBackend.includes(term),`Email booking HTML thiếu ${term}`));
JSON.parse(read('package.json'));JSON.parse(read('apps-script/content-admin/appsscript.json'));JSON.parse(read('apps-script/booking-payment/appsscript.json'));
console.log(`Smoke checks passed: ${packages.length} packages, configs and deployment artifacts valid.`);
